### PR TITLE
Added a filter for DataFiles to exlude the debian control folder

### PR DESCRIPTION
**Pull request by stamp**
Hi guys!

What do you think about this solution?

Related to: https://github.com/laher/goxc/pull/109

### CODE REVIEW

**Comment by stamp** [comment]
Just to clearify:

Its lines 340 to 344 that have been changed. All the other changes are changes that gofmt did.

**Comment by pdf** [comment]
Can you gofmt in one commit, then make your changes?  It's too hard to see what's going on here.

**Comment by stamp** [comment]
Good idea! :) Made some new commits

**Comment by laher** [comment]
man so sorry I missed this. 4 years later ...

**Pull request merged**
